apiVersion: apps/v1
kind: Deployment
metadata:
  name: motive-back-end-deployment
spec:
  template:
    metadata:
      name: motive-back-end-pod
      labels:
        app: motive-back-end
    spec:
      containers:
        - name: motive-back-end-container
          image: docker.io/yaskovdev/motive-back-end:latest
          env:
            - name: DATABASE_URL
              value: "$DATABASE_JDBC_URL"
            - name: DATABASE_USERNAME
              value: "$DATABASE_USERNAME"
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: $APP_DATABASE_NAME-postgresql
                  key: postgres-password
                  optional: false
          ports:
            - containerPort: 8080
  replicas: 1
  selector:
    matchLabels:
      app: motive-back-end
---
apiVersion: v1
kind: Service
metadata:
  name: motive-back-end-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: motive-back-end
