apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ssl-tls-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - api.motivepick.com
      secretName: app-web-cert
  rules:
    - host: api.motivepick.com
      http:
        paths:
          - backend:
              serviceName: motive-back-end-service
              servicePort: 80
            path: /
